language: node_js

node_js:
  - "8"
before_install:
  - "curl https://install.meteor.com/ | sh"
before_script:
  - "export PATH=$HOME/.meteor:$PATH"

script:
  - "meteor test-packages packages/job-collection --driver-package meteortesting:mocha --once"
